server:

	listen:
		127.0.0.1:8000

	server_name             :             [example.com]


	error_pages:
		400:/index/400.html
		500:/html_errors/500ErrorPage.html
		404:/BadRequestPage.htm
	max_body_size: 1000

	root: ./data
	index: root_index.html

	locations:

		- path: /some/ran
			allowed_methods:     " GET|POST|DELETE"             
			index: index.html
	
		- path: /some/random/dir2
			allowed_methods: "GET  | POST"
			index:       index.html
			root: /w3
			autoindex: on

		- path: /old-url
			autoindex: on
			redirect: 301 /new-url
			index        :       index.html_errors
	
	cgi:
		- path: /cgi-bin
			pass_to: .py /usr/bin/python3
			pass_to: .js /home/kvalerii/.nvm/versions/node/v22.21.1/bin/node
			allowed_methods: "GET|POST"

server:

	listen:
		127.0.0.5:8000

	server_name             :             [example.com]

	root: ./data
	index: root_index.html

	locations:

		- path: /some/ran
			allowed_methods:     " GET|POST|DELETE"             
			index: index.html
	
		- path: /some/random/dir2
			allowed_methods: "GET  | POST"
			index:       index.html
			root: /w3
			autoindex: on

		- path: /old-url
			autoindex: on
			redirect: 301 /new-url
			index        :       index.html_errors
	
	cgi:
		- path: /cgi-bin
			pass_to: .php1 /usr/bin/php
			pass_to: .php /usr/bin/php
			pass_to: .php3 /usr/bin/php
			pass_to: .php4 /usr/bin/php
			allowed_methods: "GET|POST"

	error_pages:
		400:/index/400.html
		500:/html_errors/500ErrorPage.html
		404:/BadRequestPage.htm
	max_body_size: 1000