server:
	listen:
		127.0.0.1:3490

	root: ./data
	index: index.html

	locations:
		- path: /
			allowed_methods: "GET"

		- path: /post_body
			max_body_size: 1000000000
			allowed_methods: "POST"

		- path: /directory
			allowed_methods: "GET"
			index: youpi.bad_extension
			root: YoupiBanane

		- path: /YoupiBanane
			allowed_methods: "GET"
			index: youpi.bad_extension

	cgi:
		- pass_to: /home/rmzvr/Desktop/webserv/data/YoupiBanane/cgi_test
			extensions: ".bla"