server:

	listen:
		127.0.0.1:8000

	server_name: [example.com]

	error_pages:
		400:/index/400.html
		500:/html_errors/500ErrorPage.html
		404:/BadRequestPage.html

	max_body_size: 1000

	root: /data
	index index.html
	
  default_allowed_methods: [GET]
	
	locations:

		- path: /some/random/dir:
			allowed_methods: "GET|POST|PUT"
			default: index.html
	
		- path: /some/random/dir2:
			allowed_methods: "GET|POST|PUT"
			default: index.html
			root: /w3
			autoindex: on

		- path: /old-url:
		  return: 301 /new-url
	
	cgi:
		- path: cgi-bin:
			pass_to: /usr/bin/python3
			extension: .py
			allowed_methods: "GET|POST|PUT"

