server:

	listen:
		127.0.0.1:3490

	server_name             :             [example.com]


	error_pages:
		400:/index/400.html
		500:/html_errors/500ErrorPage.html
		404:/BadRequestPage.html
	max_body_size: 1000

	root: data
	index: root_index.html

	locations:
		- path: /
			allowed_methods: "GET  | POST"
			index:       index.html
		- path: /videos
			allowed_methods: "GET  | POST"
			index:       index.html
			autoindex: on

	cgi:
		- path: /cgi-bin
			pass_to: .py /usr/bin/python3
			pass_to: .js /usr/bin/node
			allowed_methods: "GET|POST"

server:

	listen:
		127.0.0.5:8000

	server_name             :             [example.com]

	root: data
	index: root_index.html

	locations:

		- path: /some/random/dir2
			allowed_methods:     " GET|POST|DELETE"             
			index: index.html

		- path: /some/random
			allowed_methods: "GET  | POST"
			index:       index.html
			autoindex: on

	cgi:
		- path: /cgi-bin
			pass_to: .php /usr/bin/node
			allowed_methods: "GET|POST"

	error_pages:
		400:/index/400.html
		500:/html_errors/500ErrorPage.html
		404:/BadRequestPage.html
	max_body_size: 1000