server:
	listen:
		127.0.0.1:8000

	server_name: 1server.com

	error_pages:
		500:/html_errors/500ErrorPage.html
		501:/BadRequestPage.html
	max_body_size: 1000

	root: data
	index: root_index.html

	locations:
		- path: /some/ran
			allowed_methods:     " GET|POST|DELETE"             
			index:       index.html

		- path: /some/random/dir2
			allowed_methods: "GET  | POST"
			index:   index.html
			root: /w3
			autoindex: on

		- path:/old-url
			autoindex: on
			return: 301 /new-url
			index        :       index.html_errors

	cgi:
		- path: /cgi-bin
			pass_to: /usr/bin/python3
			extension: .py
			allowed_methods: "GET|POST"

server:

	listen:
		127.0.0.1:8000

	server_name             :             example.com


	error_pages:
		500:/html_errors/500ErrorPage.html
		501:/BadRequestPage.html
	max_body_size: 1000

	root: ./data
	index: root_index.html

	locations:
		- path: /some/ran
			allowed_methods:     " GET|POST|DELETE"             
			index:       index.html

		- path: /some/random/dir2
			allowed_methods: "GET  | POST"
			index:   index.html
			root: /testdata
			autoindex: on

	cgi:
		- path: /cgi-bin
			pass_to: /usr/bin/python3
			extension: .py
			allowed_methods: "GET|POST"