server:
	listen:
		127.0.0.1:3490

	error_pages:
		400: /BadRequestPage.html

	root: ./data
	index: index.html

	locations:
		- path: /
			allowed_methods: "GET|POST"
			max_body_size: 100000000000

		- path: /old
			allowed_methods: "GET"
			redirect: 301 /new

		- path: /new
			allowed_methods: "GET"
			autoindex: on

		- path: /post_body
			max_body_size: 1000000000
			allowed_methods: "GET|POST|DELETE"
			index: 0-upload.txt
			autoindex: on

		- path: /directory
			allowed_methods: "GET"
			index: youpi.bad_extension
			root: YoupiBanane

		- path: /videos
			allowed_methods: "GET|POST|DELETE"
			max_body_size: 1000
			autoindex: on

		- path: /YoupiBanane
			allowed_methods: "GET"
			index: youpi.bad_extension

	cgi:
		- pass_to: /home/rmzvr/Desktop/webserv/YoupiBanane/cgi_test
			extensions: ".bla"
		- pass_to: /usr/bin/php
			extensions: ".php"
		- pass_to: /usr/bin/node
			extensions: ".js"
		- pass_to: /usr/local/bin/python
			extensions: ".py"

server:
	listen:
		127.0.0.5:8000

	root: ./data
	index: root_index.html

	locations:
		- path: /
			allowed_methods: "GET"

		- path: /some/random/dir2
			allowed_methods: "GET|POST|DELETE"
			index: index.html

		- path: /some/rando
			allowed_methods: "GET|POST"
			index: index.html
			max_body_size: 1000
			autoindex: on

	error_pages:
		400: /index/400.html
		500: /html_errors/500ErrorPage.html
		404: /BadRequestPage.html