#!/usr/bin/env bash
# Webserv Siege Stress Tests
# Generated by webserver test panel
# Requires: siege (sudo apt install siege)

set -e
echo "Starting stress tests..."
echo "Make sure your webserver is running on 127.0.0.1:3490 and 127.0.0.5:8000"
echo ""

# Basic availability (25c 30s)
# 25 concurrent users hammering / for 30s. Server must stay alive and serve all requests. Target: 100% availability, 0 failed transactions.
echo ""
echo "=== Basic availability (25c 30s) ==="
siege -c 25 -t 30S http://127.0.0.1:3490/


# High concurrency (100c 30s)
# 100 concurrent connections. Tests epoll/poll scalability. Availability should stay near 100%. Any drop indicates a blocking call or fd leak.
echo ""
echo "=== High concurrency (100c 30s) ==="
siege -c 100 -t 30S http://127.0.0.1:3490/


# Static file throughput (50c 20s)
# Static file serving under load. Should saturate bandwidth before dropping requests. Verify response time stays stable.
echo ""
echo "=== Static file throughput (50c 20s) ==="
siege -c 50 -t 20S http://127.0.0.1:3490/index.html


# POST flood (50c 20s)
# POST requests under load to /post_body/. Tests write-path non-blocking I/O. 0 failed transactions expected.
echo ""
echo "=== POST flood (50c 20s) ==="
siege -c 50 -t 20S --content-type 'text/plain' 'http://127.0.0.1:3490/post_body/ POST hello'


# CGI under load (20c 20s)
# 20 concurrent CGI (python) requests. Each forks a process — tests that server does not exhaust fds or processes. No failed transactions.
echo ""
echo "=== CGI under load (20c 20s) ==="
siege -c 20 -t 20S http://127.0.0.1:3490/cgi-bin/cgi.py


# Mixed URLs (50c 30s)
# Multiple URLs in rotation. Creates /tmp/siege_urls.txt with GET /, /index.html, /0-upload.txt, /new/. Tests routing under concurrent load.
echo ""
echo "=== Mixed URLs (50c 30s) ==="
cat > /tmp/siege_urls.txt << 'URLS'
http://127.0.0.1:3490/
http://127.0.0.1:3490/index.html
http://127.0.0.1:3490/0-upload.txt
http://127.0.0.1:3490/new/
URLS
siege -c 50 -t 30S -f /tmp/siege_urls.txt


# Keep-alive connections (50c 30s)
# Forces keep-alive. Tests that server reuses connections correctly and does not leak sockets. Watch for fd exhaustion in server logs.
echo ""
echo "=== Keep-alive connections (50c 30s) ==="
siege -c 50 -t 30S --header="Connection: keep-alive" http://127.0.0.1:3490/


# Large POST body (10c 200r)
# 512KB body x 10 concurrent, 200 requests. Uses /post_body/ (trailing slash) to avoid redirect. Target: 0 failed requests.
echo ""
echo "=== Large POST body (10c 200r) ==="
python3 -c "open('/tmp/siege_body.txt','w').write('x'*512*1024)"
ab -n 200 -c 10 -p /tmp/siege_body.txt -T 'text/plain' http://127.0.0.1:3490/post_body/


# Connection limit (200c 15s)
# 200 concurrent — pushes fd and epoll limits. Server must not crash or hang. Some 503/timeout acceptable but process must stay alive.
echo ""
echo "=== Connection limit (200c 15s) ==="
siege -c 200 -t 15S http://127.0.0.1:3490/


# CGI timeout under load (20c 30s)
# Hammers sleep.py (infinite loop). Every request returns 504 after CGI_TIMEOUT (10s). Siege counts 504 as failed so 0% availability is expected. Key checks: longest_transaction ≈10s (timeout fires on time), server does not crash, no zombies (ps aux | grep python).
echo ""
echo "=== CGI timeout under load (20c 30s) ==="
siege -c 20 -t 30S http://127.0.0.1:3490/cgi-bin/sleep.py


# Server 2 — basic load (25c 20s)
# Basic availability test for the second server (127.0.0.5:8000). Verifies both servers handle concurrent load independently.
echo ""
echo "=== Server 2 — basic load (25c 20s) ==="
siege -c 25 -t 20S http://127.0.0.5:8000/

echo ""
echo "=== All stress tests complete ==="
